# coding: utf-8

"""
    Farsava API

    Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.  # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: amir@amerandish.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ASRRequestBodyData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'config': 'RecognitionConfig',
        'audio': 'RecognitionAudioData'
    }

    attribute_map = {
        'config': 'config',
        'audio': 'audio'
    }

    def __init__(self, config=None, audio=None):  # noqa: E501
        """ASRRequestBodyData - a model defined in OpenAPI"""  # noqa: E501

        self._config = None
        self._audio = None
        self.discriminator = None

        self.config = config
        self.audio = audio

    @property
    def config(self):
        """Gets the config of this ASRRequestBodyData.  # noqa: E501


        :return: The config of this ASRRequestBodyData.  # noqa: E501
        :rtype: RecognitionConfig
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this ASRRequestBodyData.


        :param config: The config of this ASRRequestBodyData.  # noqa: E501
        :type: RecognitionConfig
        """
        if config is None:
            raise ValueError("Invalid value for `config`, must not be `None`")  # noqa: E501

        self._config = config

    @property
    def audio(self):
        """Gets the audio of this ASRRequestBodyData.  # noqa: E501


        :return: The audio of this ASRRequestBodyData.  # noqa: E501
        :rtype: RecognitionAudioData
        """
        return self._audio

    @audio.setter
    def audio(self, audio):
        """Sets the audio of this ASRRequestBodyData.


        :param audio: The audio of this ASRRequestBodyData.  # noqa: E501
        :type: RecognitionAudioData
        """
        if audio is None:
            raise ValueError("Invalid value for `audio`, must not be `None`")  # noqa: E501

        self._audio = audio

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ASRRequestBodyData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
