# coding: utf-8

"""
    Farsava API

    Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.  # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: amir@amerandish.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class SynthesisInput(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'text': 'str',
        'ssml': 'str'
    }

    attribute_map = {
        'text': 'text',
        'ssml': 'ssml'
    }

    def __init__(self, text=None, ssml=None):  # noqa: E501
        """SynthesisInput - a model defined in OpenAPI"""  # noqa: E501

        self._text = None
        self._ssml = None
        self.discriminator = None

        if text is not None:
            self.text = text
        if ssml is not None:
            self.ssml = ssml

    @property
    def text(self):
        """Gets the text of this SynthesisInput.  # noqa: E501

        The raw text to be synthesized.  # noqa: E501

        :return: The text of this SynthesisInput.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this SynthesisInput.

        The raw text to be synthesized.  # noqa: E501

        :param text: The text of this SynthesisInput.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def ssml(self):
        """Gets the ssml of this SynthesisInput.  # noqa: E501

        The SSML document to be synthesized. The SSML document must be valid and well-formed.  # noqa: E501

        :return: The ssml of this SynthesisInput.  # noqa: E501
        :rtype: str
        """
        return self._ssml

    @ssml.setter
    def ssml(self, ssml):
        """Sets the ssml of this SynthesisInput.

        The SSML document to be synthesized. The SSML document must be valid and well-formed.  # noqa: E501

        :param ssml: The ssml of this SynthesisInput.  # noqa: E501
        :type: str
        """

        self._ssml = ssml

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SynthesisInput):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
