# coding: utf-8

"""
    Farsava API

    Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.  # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: amir@amerandish.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class TTSResponseBody(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'audio_content': 'str'
    }

    attribute_map = {
        'audio_content': 'audioContent'
    }

    def __init__(self, audio_content=None):  # noqa: E501
        """TTSResponseBody - a model defined in OpenAPI"""  # noqa: E501

        self._audio_content = None
        self.discriminator = None

        if audio_content is not None:
            self.audio_content = audio_content

    @property
    def audio_content(self):
        """Gets the audio_content of this TTSResponseBody.  # noqa: E501

        The audio data bytes encoded as specified in the request, including the header (For LINEAR16 audio, we include the WAV header). A base64-encoded string.   # noqa: E501

        :return: The audio_content of this TTSResponseBody.  # noqa: E501
        :rtype: str
        """
        return self._audio_content

    @audio_content.setter
    def audio_content(self, audio_content):
        """Sets the audio_content of this TTSResponseBody.

        The audio data bytes encoded as specified in the request, including the header (For LINEAR16 audio, we include the WAV header). A base64-encoded string.   # noqa: E501

        :param audio_content: The audio_content of this TTSResponseBody.  # noqa: E501
        :type: str
        """

        self._audio_content = audio_content

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TTSResponseBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
