# coding: utf-8

"""
    Farsava API

    Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.  # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: amir@amerandish.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aiofarsava
from aiofarsava.farsava_model.asr_request_body_data import ASRRequestBodyData  # noqa: E501
from aiofarsava.rest import ApiException


class TestASRRequestBodyData(unittest.TestCase):
    """ASRRequestBodyData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testASRRequestBodyData(self):
        """Test ASRRequestBodyData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aiofarsava.models.asr_request_body_data.ASRRequestBodyData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
