# coding: utf-8

"""
    Farsava API

    Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.  # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: amir@amerandish.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aiofarsava
from farsava_api.language_model_api import LanguageModelApi  # noqa: E501
from aiofarsava.rest import ApiException


class TestLanguageModelApi(unittest.TestCase):
    """LanguageModelApi unit test stubs"""

    def setUp(self):
        self.api = farsava_api.language_model_api.LanguageModelApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_language_model_by_id(self):
        """Test case for get_language_model_by_id

        GET /speech/languagemodels/{languageModelId}  # noqa: E501
        """
        pass

    def test_get_language_model_list(self):
        """Test case for get_language_model_list

        GET /speech/languagemodels  # noqa: E501
        """
        pass

    def test_train_language_model(self):
        """Test case for train_language_model

        POST /speech/languagemodels  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
