# coding: utf-8

"""
    Farsava API

    Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.  # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: amir@amerandish.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aiofarsava
from aiofarsava.farsava_model.word_info import WordInfo  # noqa: E501
from aiofarsava.rest import ApiException


class TestWordInfo(unittest.TestCase):
    """WordInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWordInfo(self):
        """Test WordInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = aiofarsava.models.word_info.WordInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
