# coding: utf-8

"""
    Farsava API

    Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.  # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: amir@amerandish.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aiofarsava
from farsava_api.voice_api import VoiceApi  # noqa: E501
from aiofarsava.rest import ApiException


class TestVoiceApi(unittest.TestCase):
    """VoiceApi unit test stubs"""

    def setUp(self):
        self.api = farsava_api.voice_api.VoiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_voices_list(self):
        """Test case for get_voices_list

        GET /voice/speakers  # noqa: E501
        """
        pass

    def test_synthesize(self):
        """Test case for synthesize

        POST /voice/tts  # noqa: E501
        """
        pass

    def test_voice_health_check(self):
        """Test case for voice_health_check

        GET /voice/healthcheck  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
