# coding: utf-8

"""
    Farsava API

    Farsava API. Speech Recognition and Text to Speech by applying powerful deep neural network models.  # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: amir@amerandish.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import aiofarsava
from farsava_api.speech_api import SpeechApi  # noqa: E501
from aiofarsava.rest import ApiException


class TestSpeechApi(unittest.TestCase):
    """SpeechApi unit test stubs"""

    def setUp(self):
        self.api = farsava_api.speech_api.SpeechApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_transcription(self):
        """Test case for delete_transcription

        DELETE /speech/transcriptions/{transcriptionId}  # noqa: E501
        """
        pass

    def test_get_transcription(self):
        """Test case for get_transcription

        GET /speech/transcriptions/{transcriptionId}  # noqa: E501
        """
        pass

    def test_recognize(self):
        """Test case for recognize

        POST /speech/asr  # noqa: E501
        """
        pass

    def test_recognize_live(self):
        """Test case for recognize_live

        GET /speech/asrlive  # noqa: E501
        """
        pass

    def test_recognize_long_running(self):
        """Test case for recognize_long_running

        POST /speech/asrlongrunning  # noqa: E501
        """
        pass

    def test_speech_health_check(self):
        """Test case for speech_health_check

        GET /speech/healthcheck  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
